#以下用于App启动时，使用自带tomcat的项目根目录和端口的配置
#server.servlet.context-path=/autof8
server.port: 8081
spring.application.name: autof8

#连接池配置，需要在pom.xml中增加阿里巴巴的druid连接池依赖
spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
mybatis.mapper-locations: classpath:mapper/*.xml
mybatis.configuration.auto-mapping-behavior: full
#spring.thymeleaf.mode: LEGACYHTML5
spring.thymeleaf.mode: HTML
#关闭缓存
spring.thymeleaf.cache: false
spring.mvc.static-path-pattern: /**
#/表springmvc的web启动页的根目录webapp，/templates表springboot启动页面的根目录resources/templates(默认是static静态资源目录)，
spring.mvc.view.prefix: /
#表示web启动首页的格式必须是.jsp结尾。此时web.xml里的<welcome-file-list>顺序无效
#如果多种配置文件，会随机读取application.yml(springboot-html)、application.properties(sprinbmvc-jsp)，bootstrap.yml是springcloud的配置
spring.mvc.view.suffix: .jsp
spring.mvc.favicon.enabled: false
#旧版驱动mysql.5.1.47，已废弃
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#新版驱动mysql.6.1.6
#mysql-connector-java 6比m5多了useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#用于6以上版本mysql，MySQL 5.5.45+，6+版本默认要求建立SSL连接。
spring.datasource.name: epet
spring.datasource.url: jdbc:mysql://localhost:3306/epet?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
spring.datasource.username: root
spring.datasource.password: root
#druid连接池的配置信息# 初始化大小，最小，最大
spring.druid.initialSize: 50
spring.druid.minIdle: 5
spring.druid.maxActive: 20
#解决spring boot整合mybatis时 返回map value为空字段不显示
mybatis.configuration.call-setters-on-nulls: true
#解决乱码
code.string: UTF-8

#可有可无的配置
#引用类时，可简写，配置mapper.xml文件中，如com.entity.User在User,resultType="user"写成User
mybatis.type-aliases-package: com.entity