server:
  port: 9100

spring:
  application:
    name: configserver
  profiles:
    active: dev

---

#开发环境
#默认端口8080，Edit...配置的VM options:-Dserver.port=9100>git:http://localhost:9100/master/apigateway-dev.yml高于>bootstrap.yml/application.yml
server:
  port: 9100

#服务名称,不在git指定，在boostrap.yml指定
spring:
  application:
    name: configserver
  profiles: dev
  #指定从哪个配置中心读取，读取git配置，必须把application.yml改为bootstrap.yml,不在git指定，在boostrap.yml指定
  #本地配置和远程GIT部署https://blog.csdn.net/t610654893/article/details/82893000

  #引用类带mysql相关？，必须配置以下数据库内容！。
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #用于6以上版本mysql，MySQL 5.5.45+，6+版本默认要求建立SSL连接。
    url: jdbc:mysql://localhost:3306/shiro?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/f8xn/springcloud
          username: jiance520@163.com
          password: 1983love
          timeout: 5
          default-label: master

#  mvc:
#    static-path-pattern: /**
#    favicon:
#      enabled: false
#    view:
#      prefix: /templates #classpath:/templates/
#      suffix: .html
#  thymeleaf:
#    cache: false #关闭缓存
#    mode: HTML #LEGACYHTML5
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    auto-mapping-behavior: full
#    #解决spring boot整合mybatis时 返回map value为空字段不显示
#    call-setters-on-nulls: true
#  #可有可无的配置
#  #引用类时，可简写，配置mapper.xml文件中，如com.entity.User在User,resultType="user"写成User
#  type-aliases-package: com.entity

#指定注册中心地址,不在git指定，在boostrap.yml指定
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #配置中心访问出错，路径不对：修改所有的注册中心，增加下面配置
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

---

#测试环境
server:
  port: 9100

spring:
  application:
    name: configserver
  profiles: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/f8xn/springcloud
          username: jiance520@163.com
          password: 1983love
          timeout: 5
          default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://106.13.100.117:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

---

#生产环境
server:
  port: 9100

spring:
  application:
    name: configserver
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.100.117:3306/shiro?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: autof8Ol10
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/f8xn/springcloud
          username: jiance520@163.com
          password: 1983love
          timeout: 5
          default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://106.13.100.117:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true